apiVersion: v1
kind: ReplicationController
metadata:
  name: dash-replicas
spec:
  replicas: 2
  selector:
    app: dash
  template:
    metadata:
      labels:
        app: dash
    spec:
      containers:
      - name: dash
        image: reinaldoossuna/dash-app
        ports:
        - containerPort: 80
