Description: >
    Capstone project for Cloud DevOps Engineering Nanodegree

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
 
Resources:

  ControlPlaneRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  EKS:
    Type: AWS::EKS::Cluster
    Properties:
      Version: '1.14'
      RoleArn: !GetAtt ControlPlaneRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-Default-SG"
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                !Sub ${EnvironmentName}-SN
Outputs:

  ControlPlaneRoleArn:
    Description: ControlPanel's Role
    Value: !GetAtt ControlPlaneRole.Arn

  EKSName:
    Value: !Ref EKS
    Export:
      Name: !Sub ${EnvironmentName}-EKS
