Description: >
  Cloud DevOps Project
  UdagramAPP Servers
  
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
  KeyName:
    Description: key
    Type: String

Resources:

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      NodegroupName: !Sub "${EnvironmentName}-NodeGroup"
      AmiType: "AL2_x86_64"
      ClusterName:
                Fn::ImportValue: !Sub "${EnvironmentName}-EKS"
      DiskSize: 8
      InstanceTypes:
        - "t3.medium"
      NodeRole: !GetAtt NodeInstanceRole.Arn
      RemoteAccess:
        Ec2SshKey: !Ref KeyName
      ScalingConfig:
        DesiredSize: 1
        MinSize: 1
        MaxSize: 5
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              !Sub ${EnvironmentName}-SN
